### ISSUE TITLE
I cannot reset my default system settings after uninstall your app

### ISSUE THREAD

**Issue by deltat1995** [emrsmsrli/Caffeine#4]
I try to install your app on my device Huawei Mate 10 Pro, but it work partly, because the device keep always on the screen, but i cannot set any timeout neither with its app nor with the settings. Now i decide to unistall this app and i cannot open anymore the display setting. Please help me. I want to reset my phone.

**Comment by emrsmsrli** [comment]
The app does not change any of the phone settings. It just gets a wakelock from the system which prevents the system from turning the screen off. This could be bugged but I don't think the problem is because of Caffeine.
A simple restart to your phone should solve the issue if that's the problem. Sorry for not being able to to anything more.

**Comment by deltat1995** [comment]
i resolve it now. The restart of phone not work, but fortunally i use the optimise menu of battery's settings and it suggest me to reduce the timeout to 15 second, so i press the optimise's button and now all works. Try to make the app less invasive and reversible.

**Comment by emrsmsrli** [comment]
The app actually does nothing to invade your phone. As I said before, should be an OS bug or something. Sorry for the trouble.
